### ISSUE TITLE
dockerignore 问题

### ISSUE THREAD

**Issue by Hanmo123** [hyperf/hyperf-skeleton#125]
dockerignore规则导致migrations和seeders不会被打包进镜像，导致在docker环境下无法执行migrate和db:seed（手动去除后也需要先docker exec xxx composer install安装依赖），这是疏忽还是处于一些考虑？

https://github.com/hyperf/hyperf-skeleton/blob/master/.dockerignore

**Comment by limingxinleo** [comment]
这个自己按照实际情况，进行修改
