### ISSUE TITLE
composer create-project报错

### ISSUE THREAD

**Issue by uu-myheart** [hyperf/hyperf-skeleton#62]
执行命令 composer create-project hyperf/hyperf-skeleton 后报错
安装提示全部选择了默认
![image](https://user-images.githubusercontent.com/18180275/115221994-d34bc500-a13c-11eb-9d3c-2bd4515d7f2b.png)

使用了docker官方 php8.0-alpine镜像环境，详情如下图
![image](https://user-images.githubusercontent.com/18180275/115222110-f4acb100-a13c-11eb-9ee0-c32b28ac715a.png)

**Comment by limingxinleo** [comment]
Hyperf暂不支持php8
