### ISSUE TITLE
composer create-project 流程的 config center 步骤缺少部分套件安装

### ISSUE THREAD

**Issue by liaosankai** [hyperf/hyperf-skeleton#72]
### 环境
WSL2 on window10
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

### 问题描述
透过 `composer create-project hyperf/hyperf-skeleton path/to/install` 初始化項目，过程中选用了 Apollo
![Snipaste_2021-09-07_11-36-21](https://user-images.githubusercontent.com/82476/132280649-ecdacc9b-5ce8-4a05-8733-65818dfa23b6.png)

接下 `composer start` 启动会发生下列错误
```
> php ./bin/hyperf.php start
PHP Fatal error:  Uncaught Error: Class 'Hyperf\ConfigNacos\Constants' not found in /home/ubuntu/hyperf-skeleton/config/autoload/config_center.php:37
Stack trace:
```

### 临时解决方案
补安装 `composer require hyperf/config-nacos` 后正常。不过这点流程上 apollo 却必需安装 nacos 相关套件，这部分是否要再调整？

### 备注
若改选用了 nacos 则变成 `composer start` 发生了 `PHP Fatal error:  Uncaught Error: Class 'Hyperf\ConfigApollo\PullMode' not found`，一样透过 `composer require hyperf/config-apollo` 补安装后正常

**Comment by limingxinleo** [comment]
composer create-project hyperf/hyperf-skeleton test dev-dev

测试一下

**Comment by liaosankai** [comment]
### 測試回報
使用 composer create-project hyperf/hyperf-skeleton test dev-dev 安装项目，重新尝试选择 apollo 或 nacos ，上述问题已不再发生
