### ISSUE TITLE
Undefined constant "SWOOLE_HOOK_ALL" in /www/wwwroot/hyperf-skeleton/bin/hyperf.php:18

### ISSUE THREAD

**Issue by andy236726493** [hyperf/hyperf-skeleton#79]
1.composer create-project hyperf/hyperf-skeleton    安装成功
2. php bin/hyperf.php start   启动时， 出现下面出错:

Fatal error: Uncaught Error: Undefined constant "SWOOLE_HOOK_ALL" in /www/wwwroot/hyperf-skeleton/bin/hyperf.php:18
Stack trace:
#0 {main}
  thrown in /www/wwwroot/hyperf-skeleton/bin/hyperf.php on line 18

**Comment by limingxinleo** [comment]
php --ri swoole 看看
