### ISSUE TITLE
composer create project安装的版本不是最新的(3.x)而是2.x

### ISSUE THREAD

**Issue by GabbyMrH** [hyperf/hyperf-skeleton#85]
## 问题描述
> 通过官网文档示例安装的Hyperf版本不是最新的(3.x)，而是2.x，即使指定要3.x也无效。
如下图:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/30254530/232357310-df1292b7-1c18-4b5e-97c7-e483d5b27c78.png">

## 其他操作(也无效)

![image](https://user-images.githubusercontent.com/30254530/232357260-b1cff679-6082-4609-9981-fe1718e9c4f1.png)

## 本机环境
- PHP：8.0.14
- Swoole：4.8.11
- Composer：2.5.5

**Comment by limingxinleo** [comment]
不要使用阿里云的源

**Comment by limingxinleo** [comment]
用官方源
