### ISSUE TITLE
hyperf 启动问题

### ISSUE THREAD

**Issue by qhlssd** [hyperf/hyperf-skeleton#91]
1. php bin/hyperf.php start 启动 服务，是否存在 php bin/hyperf.php stop 命令呢
2. 开发过程中，是否支持每次修改代码，不重启服务呢？
3. 下面的内容是chatGPT回答我的，不正确吗？
清除运行时缓存：执行以下命令可以清除 Hyperf 应用的运行时缓存，以便使新代码生效。
php bin/hyperf.php clear
Shell
重新启动应用：在清除运行时缓存后，需要停止并重新启动 Hyperf 应用，以便让新代码生效。
php bin/hyperf.php stop
php bin/hyperf.php start
Shell
这样，新的代码就可以生效了。需要注意的是，在开发环境下可以使用以下命令启动 Hyperf 应用，不需要每次修改完代码都重新启动应用。

php bin/hyperf.php start
Shell
该命令会自动监听文件变化，修改后自动重启应用。但需要注意的是，如果修改了容器中的配置等比较重要的配置，还是需要执行 php bin/hyperf.php clear 清除运行时缓存，并执行 php bin/hyperf.php stop 和 php bin/hyperf.php start 重新启动应用。

**Comment by limingxinleo** [comment]
看文档吧，文档里我记得都有写

只有 start 命令

gpt 在瞎说
