### ISSUE TITLE
hyperf 日志写入问题

### ISSUE THREAD

**Issue by qhlssd** [hyperf/hyperf-skeleton#93]
代码如下图所示，向队列推送50条消息，希望得到结果写入日志50条消息记录。实际上只写入了36条消息，并且有很多的warning提示，错误内容：sendMessage.WARNING: A possible infinite logging loop was detected and aborted. It appears some of your handler code is triggering logging, see the previous log r    ecord for a hint as to what may be the cause. [] []
谢谢，帮忙指点下~
![1685328091089](https://github.com/hyperf/hyperf-skeleton/assets/52683711/546c9d41-e35d-44f9-87ae-c9de8c9731a6)
![1685328190207](https://github.com/hyperf/hyperf-skeleton/assets/52683711/68069d77-e778-445d-847b-2a9c794a89d1)

**Comment by qhlssd** [comment]
hyperf logger版本如图
![image](https://github.com/hyperf/hyperf-skeleton/assets/52683711/45604653-1552-4091-a0bc-dc8fb051aaf1)

**Comment by limingxinleo** [comment]
monolog 的 bug，更新 hyperf 到 3.0 已做了兼容
