### ISSUE TITLE
hyperf/coroutine组件的3.0.0的composer包文件缺失

### ISSUE THREAD

**Issue by richard8768** [hyperf/hyperf-skeleton#94]
将hyperf升级到3.0并执行composer update后，会出现 Class "Hyperf\Coroutine\Exception\ChannelClosedException" not found 错误
![QQ截图20230530120726](https://github.com/hyperf/hyperf-skeleton/assets/88701717/6163be98-201f-45ce-b183-08e217cc144c)
composer.json里面的hyperf/coroutine是3.0.0版本的
![QQ截图20230530120741](https://github.com/hyperf/hyperf-skeleton/assets/88701717/a7676694-4ee9-41e0-a13c-0ac2a4a7958e)
我手动下载了github上hyperf/coroutine3.0.0的文件发行压缩包，里面确实没有Hyperf\Coroutine\Exception\ChannelClosedException这个文件
![QQ截图20230530121040](https://github.com/hyperf/hyperf-skeleton/assets/88701717/f3764ddb-db6a-4f5c-bfa8-93d45628f5d1)
hyperf/coroutine3.0.16的压缩包里面有这个文件，但我用composer require hyperf/coroutine v3.0.16安装时发现，composer无法匹配到该版本号
![QQ截图20230530121238](https://github.com/hyperf/hyperf-skeleton/assets/88701717/9484b3a8-4395-49f5-869b-b44972c72829)
请官方处理下这个问题

**Comment by huangzhhui** [comment]
请移除国内的 Packgist 源，确保使用官方源或其它确保同步到最新版本的镜像库
