### ISSUE TITLE
安装包需要手工配置的选项太过冗余

### ISSUE THREAD

**Issue by BinaryAlan** [hyperf/hyperf-skeleton#97]
根据约定大于配置原则, 使用约定（默认约定）来减少冗余的配置, 开发人员可以避免耗费大量时间在复杂的配置上, 同时可以帮助新人更快地上手。由于有明确的约定，新人无需花费过多时间来了解各种配置选项，可以更快地投入到实际开发工作中。

现在使用hyperf的骨架需要配置的选项高达11个, 实在太过繁琐，建议去除这些安装时的询问步骤

**Comment by assert6** [comment]
或者在installer 显著的地方提示: 按住Enter 默认全不安装?

**Comment by limingxinleo** [comment]
> 或者在installer 显著的地方提示: 按住Enter 默认全不安装?

嗯，我觉得这个可以

**Comment by liaochao2011** [comment]
或者第一个选项变成：“是否进入经典模式配置安装？”，输入Y则进入，否则直接按默认配置安装项目

**Comment by huangdijia** [comment]
> 或者第一个选项变成：“是否进入经典模式配置安装？”，输入Y则进入，否则直接按默认配置安装项目

有办法通过参数的方式？比如 `--full`、`--lite`

**Comment by huangdijia** [comment]
https://github.com/hyperf/hyperf/pull/5894

**Comment by YiwanGi** [comment]
+1 今天第一次使用 hyperf  安装下来后一堆配置文件和文件 作为新人总体流程体验欠佳
 建议应保持最小化骨架 以便更快上手使用 如需增加服务项目 开发者应根据文档自行增加

**Comment by huangdijia** [comment]
一般情况下，创建项目的频次不会太高。如果有比较频繁地创建项目的需求，可以定制适合自己或团队的骨架，还可以根据需要增加第三方扩展包。
