### ISSUE TITLE
hyperf3.0 使用swoole4.8.13 及swoole5.0.0以下扩展启动时报错 Fatal error: Declaration of Hyperf\Engine\Channel::push(mixed $data, float $timeout = -1): bool must be compatible with Swoole\Coroutine\Channel::push($data, $timeout = <default>)

### ISSUE THREAD

**Issue by ukhflf** [hyperf/hyperf-skeleton#99]
hyperf3.0 使用swoole4.8.13 及swoole5.0.0以下扩展启动时报错 Fatal error: Declaration of Hyperf\Engine\Channel::push(mixed $data, float $timeout = -1): bool must be compatible with Swoole\Coroutine\Channel::push($data, $timeout = <default>)
![图片](https://github.com/hyperf/hyperf-skeleton/assets/18317995/0f591062-d116-40e7-b152-4763787c4db0)

**Comment by limingxinleo** [comment]
```
composer update -oW
```

不要安装组件的时候使用 swoole5.0 实际运行的时候使用 swoole < 5.0

这两个版本的 swoole 需要不同的 `hyperf/engine` 进行适配
